baseurl = "http://libosmscout.sourceforge.net/"
languageCode = "en-us"
title = "libosmscout"
disableKinds = ["RSS", "sitemap"]
pluralizeListTitles = false
PygmentsCodeFences = true
pygmentsuseclasses = true

[[menu.main]]
    name = "Main"
    weight = 1
    identifier = "main"
    url = "/"

[[menu.main]]
    name = "API Documentation"
    weight = 4
    identifier = "api-doc"
    url = "/api-doc/html/index.html"

[[menu.main]]
    name = "Companion projects"
    weight = 7
    identifier = "companion"
    url = "/documentation/companion_projects"

[[menu.main]]
    name = "Contact"
    weight = 8
    identifier = "contact"
    url = "/documentation/contact"

[blackfriday]
angledQuotes = true
smartypantsQuotesNBSP = true
