language: cpp

cache:
  - apt

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env:
        - BUILDTOOL=meson
        - TARGET=build
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env:
        - BUILDTOOL=autoconf
        - TARGET=build
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env:
        - BUILDTOOL=cmake
        - TARGET=build
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      env:
        - BUILDTOOL=autoconf
        - TARGET=build
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env:
        - BUILDTOOL=meson
        - TARGET=build
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env:
        - BUILDTOOL=autoconf
        - TARGET=build
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env:
        - BUILDTOOL=cmake
        - TARGET=build
    - os: linux
      dist: trusty
      sudo: required
      env:
        - TARGET=website
        - secure: "pJvtHQlza3h6Zl39BdOcLCICGwtoSFHQsICM+jpjFy3BjXdlYrHWV9X7yvYZnSFCBrBOmx7zKdXo8KnRqJi536Ibh7s0irQzdqWet/XxtWJuR9af2h/T7Ajs0q+3r9S6ayFcd8sSe0t4pTezcKm0JK9c3w44mohgP+OCXo4odjJglBx8dwSjxJ9CcVqzIIgcHaO/eKEkjWvxK/Wtr2U+Z9/lmWkIGwNnfnYGxg6py5L+E+2x6wbeUKWS7/a45l/qDFDdNgJlqHlE/cmWgBUnLrdMDb+qBmcrARzW6Vy8X1vVB9Fxa/72bPvDTS7Q/D0icfkC9wScGynF/HYeQDmbQCA3fUN8LnZFqqEo1yH8VzBvjmE2s4FeRr699Mvw0CXmT0b58zLZUQ9Qg8Kz5AJoWRRKjhpRyb/VzvE4Kd+c7KMr6dbEk7u6GVsVV2hbzvdSweBeqRsgSc7BBrE81Rlc3xIHb2jibRK9pe7hIqF0sZRicJRF+Rf8y3j3RFDzQfTKfFc7taAMF3ndMvVgfYJEn/8SUzNHWlrMj9UY88AdO4b6USnaXa1duWAuz7olMsiwDaBUiA+eP7Z8MAojEO17g5mgYmNFg6N5NBNTqtyX3S9WtI/EmwfIFu2fmFJcETfbY9rzkmi/uat4PNxjbqBpySL6sjaADkXfz+MdU8TdXrE="
        - secure: "n0staubhRBIAMkEH6i35X1t69+UqQ7sWY07ceYTibHbM48zJ5kUy7L2y8bEk2Oresex/kUhGSRs79IgGJRk14Ii4i59K0s3gfz/QnhFrlqwr0Xs8UAXn+HtvtmDnJaei8PrWlDsYjXqiBR6CEQowFNU9+m8Z8lLkg4x8PviiV0XHtVgmYoeG21rVuEuf8GmuGJ93P/PN/L6H8VjCDsCJPIeWuN+K3Keava5pir+vcTNE2iZl0tEPpR0QCi5NqLOqyd1N1do8toXw0yg18LOycNYbCT7ZOQ3fjtvs639XNeJojYi1yOe/A7Vjzk3kKj2GrRbpQsV1fP50aZ8JhdbQHpwLbS2OV2GIQeQ7Pw5oCLRkI2u1kI8YYABb/qGwOd8LcGOxInYvHrDx827L/Yzno6i2KClt74VPPDFjJsy7Po6nQis5Pj4dcgzTWJp+INW98OPshdntH93fyp30sP/Y/Vl9px05zwIgrBZ6q9+B+gAe+7PJXBtL28eTktOeLE2/o5KOG4yW9EiKALd6kXCcbp8SZ8DCufwJof0YuMvdkbPXDEYvWGd6gnZA0Qrm+gop7SLNFrP7kmkQJZAnKgcwCZdfLhuEF6az6r7eSEnQCV7TJLLq8lZdyhOY8yGwdaPIFW2WaUfKNo5l8jIF4fUwOkmOyUbnz7jW3fX/USuKcl0="
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env:
        - BUILDTOOL=cmake
        - TARGET=importer
        - IMPORT_TOOL_OS=Linux
        - IMPORT_TOOL_ARCH=x86_64

before_install:
  - $TRAVIS_BUILD_DIR/ci/travis/install.sh

before_script:
  - . setupAutoconf.sh

script:
  - $TRAVIS_BUILD_DIR/ci/travis/build.sh

notifications:
  email:
    recipients:
      - tim@framstag.com
    on_success: change
    on_failure: always

deploy:
  provider: releases
  api_key:
    secure: VtjyOqGYuL4LcStX0LqFJ+3jK9ojgEUKqyO7ZjukFscxGpH6zvHGb8whgHUugu+xyb4K3sZf/uqBE1gvQsbCgAltUc1akZczN61Jlwg2kb0KQqQKMKyr944+nDrLU3H7HpdLHEBR5FgrVmggjY4BeU3XYO2e+niyccpGCj5T6ocV0N3oQ1pI1wtWC6JwWViG4JA6K4uszpj/d0koQ1ncIFkEp8C7jk/j67FeSzemDVmNaHCIJOQdOf4lR4z5JvDAjsMtEfFtPvZyo4eJuHkpc7cU2FZeWmkkTHfMRZQkVBplxExQofzaZ9oN1I5VX+kiOQltH5jCFbh+8oWxHEGir5/Hy+6WfQzIjHF40Ane/Ri521ZDrxLky5QMdC4/U2cgB1WkHwuoYlWwCyB90n2Hjn1VCNABhuVXnhAu6YY+cAf+Z5nwbh5sT3LRk1lWuC9aGOSWsG/Ye5gPIk1GyW1k/kDr89J0jyuXd065JTT371mRScME4NMaUAHt/nHqonvUXQwYwNr1wjOf3XAfHVzSiByROuaYlTBgCG01+0wpRL0DSTE5072+3r6Piab7oX7j/EHgZ2rVCxSHPT8AlPl3LpJYesfZuj1WaJMaNXTIFWLBf4H8JnkoqBwdrhHQJK/XjqPENiY3saXpvd2O3G1KY3vAeLAP2uTvAJPSR9Pj8k4=
  file: build-import/libosmscout-importer.$IMPORT_TOOL_OS.$IMPORT_TOOL_ARCH.tar.gz
  skip_cleanup: true
  on:
    tags: true
    repo: Framstag/libosmscout
    condition: $TARGET = importer
