language: cpp

cache:
  - apt

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env:
        - BUILDTOOL=autoconf
        - TARGET=build
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env:
        - BUILDTOOL=cmake
        - TARGET=build
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      env:
        - BUILDTOOL=autoconf
        - TARGET=build
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env:
        - BUILDTOOL=autoconf
        - TARGET=build
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env:
        - BUILDTOOL=cmake
        - TARGET=build
    - os: linux
      dist: trusty
      sudo: required
      env:
        - TARGET=website


before_install:
  - env
  - $TRAVIS_BUILD_DIR/ci/travis/install.sh

before_script:
  - . setupAutoconf.sh
  - env
  - pkg-config --list-all | sort
  
script:
  - $TRAVIS_BUILD_DIR/ci/travis/build.sh

notifications:
  email:
    recipients:
      - tim@framstag.com
    on_success: change
    on_failure: always

