version: '{build}'

branches:
  only:
    - master
    
os: Visual Studio 2015

environment:
  matrix:
  - COMPILER: msvc2015
    PLATFORM: x64
    CONFIGURATION: Debug
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64
  - COMPILER: msys2
    PLATFORM: x64
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64

install:
  - set
  - '%APPVEYOR_BUILD_FOLDER%\ci\appveyor\install.bat'
  
build_script:
  - '%APPVEYOR_BUILD_FOLDER%\ci\appveyor\build.bat'
  
notifications:
  - provider: Email
    to:
      - tim@framstag.com
    on_build_failure: true
    on_build_status_changed: true
          
